### ISSUE TITLE
브랜치가 너무 많음.

### ISSUE THREAD

**Issue by LJLee37** [LottoIsJotmanggame/LottoPercentage#25]
브랜치가 너무 많아 일부 지우려고 하는데 지워도 되는 브랜치는 지워주기 바래.

**Comment by Qstion05** [comment]
확인

**Comment by Qstion05** [comment]
아, 가능하면 내 브랜치 전부 지워주라, 어차피 따로 수정사항도 없고.

**Comment by Qstion05** [comment]
아니다 내가 지울게

**Comment by LJLee37** [comment]
일단 내가 안쓰는 브랜치라고 판단된 것들 삭제했어. 이 말을 너무 늦게 달았네.
